name: Nemein
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#041943'
    - '#d6d9df'
    - '#9fa7b8'
    - '#4d5a72'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
