name: Nemein
favicon: null
layout_spectrum: 0.5623548673465848
typography_spectrum: 0.0012635551393032074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.020357548724859953
  lightness: 0.9513751813210547
  saturation: 0.39405393437482417
  rhythmicContrast: 0.6124374805949628
purpose: []
